# Generated by Django 5.2.4 on 2025-09-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_applicationdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture (JPG, PNG, GIF - Max 5MB)', null=True, upload_to='profile_pictures/'),
        ),
    ]
