# Generated by Django 5.2.4 on 2025-10-01 14:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('certificate_enrollment', 'Certificate of Enrollment'), ('certificate_grades', 'Certificate of Grades'), ('certificate_indigency', 'Certificate of Indigency'), ('birth_certificate', 'Birth Certificate'), ('barangay_clearance', 'Barangay Clearance'), ('police_clearance', 'Police Clearance'), ('medical_certificate', 'Medical Certificate'), ('recommendation_letter', 'Letter of Recommendation'), ('essay', 'Essay/Personal Statement'), ('transcript', 'Official Transcript'), ('tax_return', 'Tax Return/ITR'), ('payslip', 'Payslip/Income Certificate'), ('other', 'Other Document')], max_length=100)),
                ('custom_name', models.CharField(blank=True, help_text="Custom name for 'Other' document type", max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text='Additional description or instructions for this document', null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('file_format_requirements', models.CharField(default='PDF, DOC, DOCX, JPG, PNG', help_text='Accepted file formats', max_length=100)),
                ('max_file_size_mb', models.PositiveIntegerField(default=5, help_text='Maximum file size in MB')),
            ],
            options={
                'verbose_name': 'Document Requirement',
                'verbose_name_plural': 'Document Requirements',
            },
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='file',
            field=models.FileField(help_text='Uploaded document file', upload_to='application_documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='document_requirement',
            field=models.ForeignKey(blank=True, help_text='The document requirement this file fulfills', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='core.documentrequirement'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='document_requirements',
            field=models.ManyToManyField(blank=True, help_text='Select required documents for this scholarship', related_name='scholarships', to='core.documentrequirement'),
        ),
    ]
