# Generated by Django 5.2.4 on 2025-10-01 15:01

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_documentrequirement_alter_applicationdocument_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='supporting_documents',
            field=models.FileField(blank=True, help_text='Upload supporting documents (PDF, Word, or Image files)', null=True, upload_to=core.models.user_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
