# Generated by Django 5.2.6 on 2025-10-24 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_application_supporting_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('academic', 'Academic Requirements'), ('documentation', 'Documentation Requirements'), ('eligibility', 'Eligibility Requirements'), ('additional', 'Additional Requirements')], default='eligibility', max_length=20)),
                ('description', models.TextField(help_text='Requirement description')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or clarifications', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='core.scholarship')),
            ],
            options={
                'verbose_name': 'Scholarship Requirement',
                'verbose_name_plural': 'Scholarship Requirements',
                'ordering': ['category', 'order', 'created_at'],
            },
        ),
    ]
