# Generated by Django 5.2.6 on 2025-10-25 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_scholarshiprequirement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='final_decision_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='final_decision_by',
            field=models.ForeignKey(blank=True, help_text='Admin who made the final approval/rejection decision', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='final_decision_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('osas_approved', 'OSAS Recommended for Approval'), ('osas_rejected', 'OSAS Recommended for Rejection'), ('approved', 'Approved by Admin'), ('rejected', 'Rejected by Admin'), ('additional_info_required', 'Additional Information Required')], default='pending', max_length=30),
        ),
    ]
