# Generated by Django 5.2.6 on 2025-10-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_application_final_decision_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='campus',
            field=models.CharField(blank=True, choices=[('dumingag', 'Dumingag Campus'), ('mati', 'Mati Campus'), ('canuto', 'Canuto Campus')], help_text='Select your campus', max_length=20, null=True),
        ),
    ]
